database:
  host: localhost
  port: 5432
  name: ncod_db
  user: ncod_user
  password: your_secure_password

redis:
  host: localhost
  port: 6379
  db: 0

security:
  jwt_secret: your_jwt_secret_key
  token_expire_minutes: 1440  # 24小时

virtualhere:
  server_port: 7575
  api_key: your_virtualhere_api_key
  scan_interval: 30  # 秒

master:
  host: 0.0.0.0
  port: 8000
  debug: false

slave:
  report_interval: 30  # 秒
  reconnect_delay: 5  # 秒

logging:
  level: INFO
  max_size: 10485760  # 10MB
  backup_count: 5
  loggers:
    master:
      level: INFO
      file: master.log
    slave:
      level: INFO
      file: slave.log
    device:
      level: INFO
      file: device.log
    monitor:
      level: INFO
      file: monitor.log
    auth:
      level: INFO
      file: auth.log 