/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    DeviceConnector: typeof import('./src/components/DeviceConnector.vue')['default']
    ExportProgress: typeof import('./src/components/ExportProgress.vue')['default']
    PageBreadcrumb: typeof import('./src/components/PageBreadcrumb.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./src/components/stats/StatsCard.vue')['default']
    SystemAnnouncement: typeof import('./src/components/SystemAnnouncement.vue')['default']
    UsageChart: typeof import('./src/components/stats/UsageChart.vue')['default']
    UsageGauge: typeof import('./src/components/stats/UsageGauge.vue')['default']
    UsageHeatmap: typeof import('./src/components/stats/UsageHeatmap.vue')['default']
    UsagePieChart: typeof import('./src/components/stats/UsagePieChart.vue')['default']
  }
}
